agents/urls.py
from django.urls import path
from django.contrib import admin
from .views import *
from property.views import property_grid , property_single


app_name = 'agents'

urlpatterns = [
    path('' , agents_grid , name='agents-grid') ,
    path('agent-single/<int:id>' , agent_single , name='agent-single') ,
    path('property/<str:category>' , property_grid , name='list_by_category') ,
    path('detail/<int:id>' , property_single , name='list_by_id')
]

config/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('root.urls')) ,
    path('agents-grid/' , include('agents.urls')) ,
    path('blog-grid/' , include('blogs.urls')) ,
    path('property-grid/' , include('property.urls')) 
]


urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)

root/urls.py
from django.urls import path
from .views import *
from property.views import property_single
from agents.views import agent_single
from blogs.views import blog_detail


app_name ='root'

urlpatterns = [
    path('' , home , name='home') ,
    path('about' , about , name='about') ,
    path('contact' , contact , name = 'contact') ,
    path('prperty/<int:id>' , property_single , name = 'list_by_id') ,
    path('agent_single/<int:id>' , agent_single , name = 'list_by_agent_single') ,
    path('blog_detail/<int:id>' , blog_detail , name = 'list_by_blog_detail') ,
    
]

agents/models.py
from django.db import models
from django.contrib.auth.models import User

class Agents(models.Model):
    title = models.CharField(max_length=220)
    image = models.ImageField(upload_to='agent' , default='default_property.jpg')
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    description = models.TextField()
    phone = models.CharField(max_length=110 , default=0)
    email = models.EmailField(null=True)
    facebook = models.CharField(max_length=300 , default='#')
    x = models.CharField(max_length=300 , default='#')
    instagram = models.CharField(max_length=300 , default='#')
    linkedin = models.CharField(max_length=300 , default='#')
    status = models.BooleanField(default=True)


    def __str__(self):
        return self.title




# Create your models here.

agents/views.py
from django.shortcuts import render
from .models import Agents
from property.models import Property , Category_Property


def agents_grid(request):

    agent = Agents.objects.filter(status=True)

    context={
        'agents' : agent 
    }

    return render(request , 'agents/agents-grid.html' , context=context)



def agent_single(request , id):

    agent = Agents.objects.get(id=id)

    context={
        'agent' : agent ,
        'property' : Property.objects.filter(status=True) ,
        'category' : Category_Property.objects.filter(status=True)
    }

    return render(request , 'agents/agent-single.html' , context=context)




# Create your views here.

templates/agents/agent-single.html
{% extends "base.html" %}
{% load static %}
{% block 'title' %}Agent Single{% endblock 'title' %}
{% block 'content' %}

  <main id="main">

    <!-- ======= Intro Single ======= -->
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">{{agent.user.username}}</h1>
              <span class="color-text-a">Agent Immobiliari</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                  <a href="#">Agents</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  {{agent.user.username}}
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section><!-- End Intro Single -->

    <!-- ======= Agent Single ======= -->
    <section class="agent-single">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="row">
              <div class="col-md-6">
                <div class="agent-avatar-box">
                  <img src={{agent.image.url}} alt="" class="agent-avatar img-fluid">
                </div>
              </div>
              <div class="col-md-5 section-md-t3">
                <div class="agent-info-box">
                  <div class="agent-title">
                    <div class="title-box-d">
                      <h3 class="title-d">
                        {{agent.user.username}}
                      </h3>
                    </div>
                  </div>
                  <div class="agent-content mb-3">
                    <p class="content-d color-text-a">
                      {{agent.description}}
                    </p>
                    <div class="info-agents color-a">
                      <p>
                        <strong>Phone: </strong>
                        <span class="color-text-a">{{agent.phone}}</span>
                      </p>
                      {% comment %} <p>
                        <strong>Mobile: </strong>
                        <span class="color-text-a"> 999 123 456 789</span>
                      </p> {% endcomment %}
                      <p>
                        <strong>Email: </strong>
                        <span class="color-text-a">{{agent.email}}</span>
                      </p>
                      {% comment %} <p>
                        <strong>skype: </strong>
                        <span class="color-text-a"> Margaret.Es</span>
                      </p> {% endcomment %}
                      {% comment %} <p>
                        <strong>Email: </strong>
                        <span class="color-text-a"> agents@example.com</span>
                      </p> {% endcomment %}
                    </div>
                  </div>
                  <div class="socials-footer">
                    <ul class="list-inline">
                      <li class="list-inline-item">
                        <a href={{agent.facebook}} class="link-one">
                          <i class="bi bi-facebook" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href={{agent.x}} class="link-one">
                          <i class="bi bi-twitter" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href={{agent.instagram}} class="link-one">
                          <i class="bi bi-instagram" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href={{agent.linkedin}} class="link-one">
                          <i class="bi bi-linkedin" aria-hidden="true"></i>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-12 section-t8">
            <div class="title-box-d">
              <h3 class="title-d">My Properties (6)</h3>
            </div>
          </div>
          <div class="row property-grid grid">
            <div class="col-sm-12">
              <div class="grid-option">
                <form>
                  <select class="custom-select">
                    <option selected>All</option>
                    <option value="1">New to Old</option>
                    <option value="2">For Rent</option>
                    <option value="3">For Sale</option>
                  </select>
                </form>
              </div>
            </div>

            {% for obj in property %}
            <div class="col-md-4">
              <div class="card-box-a card-shadow">
                <div class="img-box-a">
                  <img src={{obj.image.url}} alt="" class="img-a img-fluid">
                </div>
                <div class="card-overlay">
                  <div class="card-overlay-a-content">
                    <div class="card-header-a">
                      <h2 class="card-title-a">
                        <a href="#">204 Mount
                          <br /> Olive Road Two</a>
                      </h2>
                    </div>
                    <div class="card-body-a">
                      <div class="price-box d-flex">
                        <span class="price-a">rent | $ {{obj.rent}}</span>
                      </div>
                      <a href={% url 'agents:list_by_id' id=obj.id %} class="link-a">Click here to view
                        <span class="bi bi-chevron-right"></span>
                      </a>
                    </div>
                    <div class="card-footer-a">
                      <ul class="card-info d-flex justify-content-around">
                        <li>
                          <h4 class="card-info-title">Area</h4>
                          <span>{{obj.area}}
                            <sup>2</sup>
                          </span>
                        </li>
                        <li>
                          <h4 class="card-info-title">Beds</h4>
                          <span>{{obj.beds}}</span>
                        </li>
                        <li>
                          <h4 class="card-info-title">Baths</h4>
                          <span>{{obj.baths}}</span>
                        </li>
                        <li>
                          <h4 class="card-info-title">Garages</h4>
                          <span>{{obj.garages}}</span>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {% endfor %}

          </div>
        </div>
      </div>
    </section><!-- End Agent Single -->

  </main><!-- End #main -->

  
  {% endblock 'content' %}

templates/agents/agents-grid.html
{% extends "base.html" %}
{% load static %}
{% block 'title' %}Agents Grid{% endblock 'title' %}
{% block 'content' %}

  <main id="main">
    <!-- =======Intro Single ======= -->
    <section class="intro-single">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-lg-8">
            <div class="title-single-box">
              <h1 class="title-single">Our Amazing Agents</h1>
              <span class="color-text-a">Grid Properties</span>
            </div>
          </div>
          <div class="col-md-12 col-lg-4">
            <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
              <ol class="breadcrumb">
                <li class="breadcrumb-item">
                  <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                  Agents Grid
                </li>
              </ol>
            </nav>
          </div>
        </div>
      </div>
    </section><!-- End Intro Single-->

    <!-- ======= Agents Grid ======= -->
    <section class="agents-grid grid">
      <div class="container">
        <div class="row">

          {% for obj in agents %}
          <div class="col-md-4">
            <div class="card-box-d">
              <div class="card-img-d">
                <img src={{obj.image.url}} alt="" class="img-d img-fluid">
              </div>
              <div class="card-overlay card-overlay-hover">
                <div class="card-header-d">
                  <div class="card-title-d align-self-center">
                    <h3 class="title-d">
                      <a href={% url 'agents:agent-single' id=obj.id %} class="link-two">{{obj.user.username}}
                        </a>
                    </h3>
                  </div>
                </div>
                <div class="card-body-d">
                  <p class="content-d color-text-a">
                    {{obj.description}}
                  </p>
                  <div class="info-agents color-a">
                    <p>
                      <strong>Phone: </strong>{{obj.phone}}
                    </p>
                    <p>
                      <strong>Email: </strong>{{obj.email}}
                    </p>
                  </div>
                </div>
                <div class="card-footer-d">
                  <div class="socials-footer d-flex justify-content-center">
                    <ul class="list-inline">
                      <li class="list-inline-item">
                        <a href={{obj.facebook}} class="link-one">
                          <i class="bi bi-facebook" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href={{obj.x}} class="link-one">
                          <i class="bi bi-twitter" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href={{obj.instagram}} class="link-one">
                          <i class="bi bi-instagram" aria-hidden="true"></i>
                        </a>
                      </li>
                      <li class="list-inline-item">
                        <a href={{obj.linkedin}} class="link-one">
                          <i class="bi bi-linkedin" aria-hidden="true"></i>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}

        </div>
        <div class="row">
          <div class="col-sm-12">
            <nav class="pagination-a">
              <ul class="pagination justify-content-end">
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">
                    <span class="bi bi-chevron-left"></span>
                  </a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item active">
                  <a class="page-link" href="#">2</a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="#">3</a>
                </li>
                <li class="page-item next">
                  <a class="page-link" href="#">
                    <span class="bi bi-chevron-right"></span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </section><!-- End Agents Grid-->

  </main><!-- End #main -->

  {% endblock 'content' %}